version: '2'

services:
    mongo:
        build: mongo
        image: harkirat9711/mongo:cs6320
        container_name: mongo
        volumes:
            - /tmp/mongo_logs:/logs
            - /tmp/mongo_data:/data
        ports:
            - "27017:27017"
    haproxy:
        build: haproxy
        image: harkirat9711/haproxy:cs6320
        container_name: haproxy
        volumes:
            - /tmp/haproxy_logs:/logs
        ports:
            - "80:80"

    redis:
        build: redis
        image: harkirat9711/redis:cs6320
        container_name: redis
        volumes:
            - /tmp/redis_data:/data
        ports:
            - "6379:6379"

    app1:
        build: app
        image: harkirat9711/app:cs6320
        container_name: app1
        ports:
            - "81:80"
    app2:
        build: app
        image: harkirat9711/app:cs6320
        container_name: app2
        ports:
            - "82:80"
    app3:
        build: app
        image: harkirat9711/app:cs6320
        container_name: app3
        ports:
            - "83:80"
    app4:
        build: app
        image: harkirat9711/app:cs6320
        container_name: app4
        ports:
            - "84:80"